//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibBatchPlatform
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Batch_Submit", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    
    public partial class ABC_Batch_Submit : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private LibBatchPlatform.ABC_Batch_Record[] RecordsField;
        
        private string sumField;
        
        private string totalField;
        
        private string tr_addrField;
        
        private string tr_codeField;
        
        private string tr_dateField;
        
        private string unitidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibBatchPlatform.ABC_Batch_Record[] Records
        {
            get
            {
                return this.RecordsField;
            }
            set
            {
                this.RecordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sum
        {
            get
            {
                return this.sumField;
            }
            set
            {
                this.sumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tr_addr
        {
            get
            {
                return this.tr_addrField;
            }
            set
            {
                this.tr_addrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tr_code
        {
            get
            {
                return this.tr_codeField;
            }
            set
            {
                this.tr_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tr_date
        {
            get
            {
                return this.tr_dateField;
            }
            set
            {
                this.tr_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unitid
        {
            get
            {
                return this.unitidField;
            }
            set
            {
                this.unitidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Batch_Record", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Batch_Record : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private LibBatchPlatform.ABC_Batch_BookEntry[] EntriesField;
        
        private string abc_order_noField;
        
        private string amountField;
        
        private string order_noField;
        
        private string store_idField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibBatchPlatform.ABC_Batch_BookEntry[] Entries
        {
            get
            {
                return this.EntriesField;
            }
            set
            {
                this.EntriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string abc_order_no
        {
            get
            {
                return this.abc_order_noField;
            }
            set
            {
                this.abc_order_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string order_no
        {
            get
            {
                return this.order_noField;
            }
            set
            {
                this.order_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string store_id
        {
            get
            {
                return this.store_idField;
            }
            set
            {
                this.store_idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Batch_BookEntry", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LibBatchPlatform.ABC_Batch_BookEntry_Res))]
    public partial class ABC_Batch_BookEntry : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string accno1Field;
        
        private string accno2Field;
        
        private string tramtField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accno1
        {
            get
            {
                return this.accno1Field;
            }
            set
            {
                this.accno1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accno2
        {
            get
            {
                return this.accno2Field;
            }
            set
            {
                this.accno2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tramt
        {
            get
            {
                return this.tramtField;
            }
            set
            {
                this.tramtField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Batch_BookEntry_Res", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Batch_BookEntry_Res : LibBatchPlatform.ABC_Batch_BookEntry
    {
        
        private string retcodeField;
        
        private string retmsgField;
        
        private string sysdateField;
        
        private string systraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string retcode
        {
            get
            {
                return this.retcodeField;
            }
            set
            {
                this.retcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string retmsg
        {
            get
            {
                return this.retmsgField;
            }
            set
            {
                this.retmsgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sysdate
        {
            get
            {
                return this.sysdateField;
            }
            set
            {
                this.sysdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string systrace
        {
            get
            {
                return this.systraceField;
            }
            set
            {
                this.systraceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Batch_Return", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LibBatchPlatform.ABC_Serial_Total_Res))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LibBatchPlatform.ABC_Serial_Detail_Res))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LibBatchPlatform.ABC_Order_Refund_Res))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LibBatchPlatform.ABC_Check_Payment_Res))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LibBatchPlatform.ABC_Batch_Result_Res))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LibBatchPlatform.ABC_VAccount_Query_Res))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LibBatchPlatform.ABC_Batch_Submit_Res))]
    public partial class ABC_Batch_Return : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RetCodeField;
        
        private string RetMsgField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RetCode
        {
            get
            {
                return this.RetCodeField;
            }
            set
            {
                this.RetCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RetMsg
        {
            get
            {
                return this.RetMsgField;
            }
            set
            {
                this.RetMsgField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Serial_Total_Res", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Serial_Total_Res : LibBatchPlatform.ABC_Batch_Return
    {
        
        private string SumField;
        
        private string TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sum
        {
            get
            {
                return this.SumField;
            }
            set
            {
                this.SumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Serial_Detail_Res", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Serial_Detail_Res : LibBatchPlatform.ABC_Batch_Return
    {
        
        private LibBatchPlatform.ABC_Serial_Entity[] RecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibBatchPlatform.ABC_Serial_Entity[] Records
        {
            get
            {
                return this.RecordsField;
            }
            set
            {
                this.RecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Order_Refund_Res", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Order_Refund_Res : LibBatchPlatform.ABC_Batch_Return
    {
        
        private string accno1Field;
        
        private string accno2Field;
        
        private string amountField;
        
        private string channelField;
        
        private string feeField;
        
        private string jronoField;
        
        private string refund_dateField;
        
        private string vchnoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accno1
        {
            get
            {
                return this.accno1Field;
            }
            set
            {
                this.accno1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accno2
        {
            get
            {
                return this.accno2Field;
            }
            set
            {
                this.accno2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fee
        {
            get
            {
                return this.feeField;
            }
            set
            {
                this.feeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jrono
        {
            get
            {
                return this.jronoField;
            }
            set
            {
                this.jronoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string refund_date
        {
            get
            {
                return this.refund_dateField;
            }
            set
            {
                this.refund_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vchno
        {
            get
            {
                return this.vchnoField;
            }
            set
            {
                this.vchnoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Check_Payment_Res", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Check_Payment_Res : LibBatchPlatform.ABC_Batch_Return
    {
        
        private string accept_noField;
        
        private string biztype_codeField;
        
        private string invoice_noField;
        
        private string order_amountField;
        
        private string order_noField;
        
        private string order_statusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accept_no
        {
            get
            {
                return this.accept_noField;
            }
            set
            {
                this.accept_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string biztype_code
        {
            get
            {
                return this.biztype_codeField;
            }
            set
            {
                this.biztype_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoice_no
        {
            get
            {
                return this.invoice_noField;
            }
            set
            {
                this.invoice_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string order_amount
        {
            get
            {
                return this.order_amountField;
            }
            set
            {
                this.order_amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string order_no
        {
            get
            {
                return this.order_noField;
            }
            set
            {
                this.order_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string order_status
        {
            get
            {
                return this.order_statusField;
            }
            set
            {
                this.order_statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Batch_Result_Res", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Batch_Result_Res : LibBatchPlatform.ABC_Batch_Return
    {
        
        private string ErrCntField;
        
        private LibBatchPlatform.ABC_Batch_Result_Dtl[] ErrListField;
        
        private string ErrSumField;
        
        private string SuccCntField;
        
        private string SuccSumField;
        
        private string SumField;
        
        private string TotalField;
        
        private string bankdateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrCnt
        {
            get
            {
                return this.ErrCntField;
            }
            set
            {
                this.ErrCntField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibBatchPlatform.ABC_Batch_Result_Dtl[] ErrList
        {
            get
            {
                return this.ErrListField;
            }
            set
            {
                this.ErrListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrSum
        {
            get
            {
                return this.ErrSumField;
            }
            set
            {
                this.ErrSumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuccCnt
        {
            get
            {
                return this.SuccCntField;
            }
            set
            {
                this.SuccCntField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuccSum
        {
            get
            {
                return this.SuccSumField;
            }
            set
            {
                this.SuccSumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sum
        {
            get
            {
                return this.SumField;
            }
            set
            {
                this.SumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankdate
        {
            get
            {
                return this.bankdateField;
            }
            set
            {
                this.bankdateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_VAccount_Query_Res", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_VAccount_Query_Res : LibBatchPlatform.ABC_Batch_Return
    {
        
        private string BalanceField;
        
        private string CurBalField;
        
        private LibBatchPlatform.ABC_VAccount_Dtl[] DtlListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Balance
        {
            get
            {
                return this.BalanceField;
            }
            set
            {
                this.BalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurBal
        {
            get
            {
                return this.CurBalField;
            }
            set
            {
                this.CurBalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibBatchPlatform.ABC_VAccount_Dtl[] DtlList
        {
            get
            {
                return this.DtlListField;
            }
            set
            {
                this.DtlListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Batch_Submit_Res", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Batch_Submit_Res : LibBatchPlatform.ABC_Batch_Return
    {
        
        private string BatchNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatchNo
        {
            get
            {
                return this.BatchNoField;
            }
            set
            {
                this.BatchNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Serial_Entity", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Serial_Entity : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string accno1Field;
        
        private string accno2Field;
        
        private string amountField;
        
        private string channelField;
        
        private string feeField;
        
        private string order_noField;
        
        private string store_idField;
        
        private string trdateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accno1
        {
            get
            {
                return this.accno1Field;
            }
            set
            {
                this.accno1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accno2
        {
            get
            {
                return this.accno2Field;
            }
            set
            {
                this.accno2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fee
        {
            get
            {
                return this.feeField;
            }
            set
            {
                this.feeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string order_no
        {
            get
            {
                return this.order_noField;
            }
            set
            {
                this.order_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string store_id
        {
            get
            {
                return this.store_idField;
            }
            set
            {
                this.store_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string trdate
        {
            get
            {
                return this.trdateField;
            }
            set
            {
                this.trdateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Batch_Result_Dtl", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Batch_Result_Dtl : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string accno2Field;
        
        private string amountField;
        
        private string bankOidField;
        
        private string bankdateField;
        
        private string retcodeField;
        
        private string retmsgField;
        
        private string sysdateField;
        
        private string systraceField;
        
        private string unitOidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accno2
        {
            get
            {
                return this.accno2Field;
            }
            set
            {
                this.accno2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankOid
        {
            get
            {
                return this.bankOidField;
            }
            set
            {
                this.bankOidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankdate
        {
            get
            {
                return this.bankdateField;
            }
            set
            {
                this.bankdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string retcode
        {
            get
            {
                return this.retcodeField;
            }
            set
            {
                this.retcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string retmsg
        {
            get
            {
                return this.retmsgField;
            }
            set
            {
                this.retmsgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sysdate
        {
            get
            {
                return this.sysdateField;
            }
            set
            {
                this.sysdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string systrace
        {
            get
            {
                return this.systraceField;
            }
            set
            {
                this.systraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unitOid
        {
            get
            {
                return this.unitOidField;
            }
            set
            {
                this.unitOidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_VAccount_Dtl", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_VAccount_Dtl : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string bankdateField;
        
        private string bankserField;
        
        private string noteField;
        
        private string tramtField;
        
        private string trdateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankdate
        {
            get
            {
                return this.bankdateField;
            }
            set
            {
                this.bankdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankser
        {
            get
            {
                return this.bankserField;
            }
            set
            {
                this.bankserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tramt
        {
            get
            {
                return this.tramtField;
            }
            set
            {
                this.tramtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string trdate
        {
            get
            {
                return this.trdateField;
            }
            set
            {
                this.trdateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Batch_Query", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Batch_Query : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BatchNoField;
        
        private string tr_codeField;
        
        private string unitidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatchNo
        {
            get
            {
                return this.BatchNoField;
            }
            set
            {
                this.BatchNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tr_code
        {
            get
            {
                return this.tr_codeField;
            }
            set
            {
                this.tr_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unitid
        {
            get
            {
                return this.unitidField;
            }
            set
            {
                this.unitidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Batch_Query_Res", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Batch_Query_Res : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private LibBatchPlatform.ABC_Batch_Record_Res[] RecordsField;
        
        private string statusField;
        
        private string sumField;
        
        private string totalField;
        
        private string tr_addrField;
        
        private string tr_codeField;
        
        private string tr_dateField;
        
        private string unitidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibBatchPlatform.ABC_Batch_Record_Res[] Records
        {
            get
            {
                return this.RecordsField;
            }
            set
            {
                this.RecordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sum
        {
            get
            {
                return this.sumField;
            }
            set
            {
                this.sumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tr_addr
        {
            get
            {
                return this.tr_addrField;
            }
            set
            {
                this.tr_addrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tr_code
        {
            get
            {
                return this.tr_codeField;
            }
            set
            {
                this.tr_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tr_date
        {
            get
            {
                return this.tr_dateField;
            }
            set
            {
                this.tr_dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unitid
        {
            get
            {
                return this.unitidField;
            }
            set
            {
                this.unitidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Batch_Record_Res", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Batch_Record_Res : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private LibBatchPlatform.ABC_Batch_BookEntry_Res[] EntriesField;
        
        private string abc_order_noField;
        
        private string amountField;
        
        private string order_noField;
        
        private string store_idField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibBatchPlatform.ABC_Batch_BookEntry_Res[] Entries
        {
            get
            {
                return this.EntriesField;
            }
            set
            {
                this.EntriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string abc_order_no
        {
            get
            {
                return this.abc_order_noField;
            }
            set
            {
                this.abc_order_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string order_no
        {
            get
            {
                return this.order_noField;
            }
            set
            {
                this.order_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string store_id
        {
            get
            {
                return this.store_idField;
            }
            set
            {
                this.store_idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Serial_Total_Req", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Serial_Total_Req : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string enddateField;
        
        private string startdateField;
        
        private string store_idField;
        
        private string tr_codeField;
        
        private string unitidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string enddate
        {
            get
            {
                return this.enddateField;
            }
            set
            {
                this.enddateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startdate
        {
            get
            {
                return this.startdateField;
            }
            set
            {
                this.startdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string store_id
        {
            get
            {
                return this.store_idField;
            }
            set
            {
                this.store_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tr_code
        {
            get
            {
                return this.tr_codeField;
            }
            set
            {
                this.tr_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unitid
        {
            get
            {
                return this.unitidField;
            }
            set
            {
                this.unitidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Serial_Detail_Req", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Serial_Detail_Req : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string enddateField;
        
        private string startdateField;
        
        private string store_idField;
        
        private string tr_codeField;
        
        private string unitidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string enddate
        {
            get
            {
                return this.enddateField;
            }
            set
            {
                this.enddateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startdate
        {
            get
            {
                return this.startdateField;
            }
            set
            {
                this.startdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string store_id
        {
            get
            {
                return this.store_idField;
            }
            set
            {
                this.store_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tr_code
        {
            get
            {
                return this.tr_codeField;
            }
            set
            {
                this.tr_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unitid
        {
            get
            {
                return this.unitidField;
            }
            set
            {
                this.unitidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Order_Refund_Req", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Order_Refund_Req : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string order_noField;
        
        private string store_idField;
        
        private string tr_codeField;
        
        private string tramtField;
        
        private string trdateField;
        
        private string unitidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string order_no
        {
            get
            {
                return this.order_noField;
            }
            set
            {
                this.order_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string store_id
        {
            get
            {
                return this.store_idField;
            }
            set
            {
                this.store_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tr_code
        {
            get
            {
                return this.tr_codeField;
            }
            set
            {
                this.tr_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tramt
        {
            get
            {
                return this.tramtField;
            }
            set
            {
                this.tramtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string trdate
        {
            get
            {
                return this.trdateField;
            }
            set
            {
                this.trdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unitid
        {
            get
            {
                return this.unitidField;
            }
            set
            {
                this.unitidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Check_Payment_Req", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Check_Payment_Req : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string accept_noField;
        
        private string biztype_codeField;
        
        private string invoice_noField;
        
        private string order_amountField;
        
        private string order_noField;
        
        private string tr_codeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accept_no
        {
            get
            {
                return this.accept_noField;
            }
            set
            {
                this.accept_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string biztype_code
        {
            get
            {
                return this.biztype_codeField;
            }
            set
            {
                this.biztype_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoice_no
        {
            get
            {
                return this.invoice_noField;
            }
            set
            {
                this.invoice_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string order_amount
        {
            get
            {
                return this.order_amountField;
            }
            set
            {
                this.order_amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string order_no
        {
            get
            {
                return this.order_noField;
            }
            set
            {
                this.order_noField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tr_code
        {
            get
            {
                return this.tr_codeField;
            }
            set
            {
                this.tr_codeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_Batch_Result_Req", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_Batch_Result_Req : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string batchnoField;
        
        private string tr_codeField;
        
        private string trdateField;
        
        private string unitidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string batchno
        {
            get
            {
                return this.batchnoField;
            }
            set
            {
                this.batchnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tr_code
        {
            get
            {
                return this.tr_codeField;
            }
            set
            {
                this.tr_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string trdate
        {
            get
            {
                return this.trdateField;
            }
            set
            {
                this.trdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unitid
        {
            get
            {
                return this.unitidField;
            }
            set
            {
                this.unitidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_VAccount_Query_Req", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_VAccount_Query_Req : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string enddateField;
        
        private string startdateField;
        
        private string store_idField;
        
        private string tr_codeField;
        
        private string unitidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string enddate
        {
            get
            {
                return this.enddateField;
            }
            set
            {
                this.enddateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string startdate
        {
            get
            {
                return this.startdateField;
            }
            set
            {
                this.startdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string store_id
        {
            get
            {
                return this.store_idField;
            }
            set
            {
                this.store_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tr_code
        {
            get
            {
                return this.tr_codeField;
            }
            set
            {
                this.tr_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unitid
        {
            get
            {
                return this.unitidField;
            }
            set
            {
                this.unitidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_SB_Submit", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_SB_Submit : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private LibBatchPlatform.ABC_SB_Item[] listField;
        
        private string serialField;
        
        private string settdateField;
        
        private string sumField;
        
        private string totalField;
        
        private string traddrField;
        
        private string trcodeField;
        
        private string trdateField;
        
        private string trnameField;
        
        private string trtypeField;
        
        private string unitidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibBatchPlatform.ABC_SB_Item[] list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string serial
        {
            get
            {
                return this.serialField;
            }
            set
            {
                this.serialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string settdate
        {
            get
            {
                return this.settdateField;
            }
            set
            {
                this.settdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sum
        {
            get
            {
                return this.sumField;
            }
            set
            {
                this.sumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string traddr
        {
            get
            {
                return this.traddrField;
            }
            set
            {
                this.traddrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string trcode
        {
            get
            {
                return this.trcodeField;
            }
            set
            {
                this.trcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string trdate
        {
            get
            {
                return this.trdateField;
            }
            set
            {
                this.trdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string trname
        {
            get
            {
                return this.trnameField;
            }
            set
            {
                this.trnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string trtype
        {
            get
            {
                return this.trtypeField;
            }
            set
            {
                this.trtypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unitid
        {
            get
            {
                return this.unitidField;
            }
            set
            {
                this.unitidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_SB_Item", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LibBatchPlatform.ABC_SB_Qry_Item))]
    public partial class ABC_SB_Item : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string accname1Field;
        
        private string accname2Field;
        
        private string accno1Field;
        
        private string accno2Field;
        
        private string bankname1Field;
        
        private string bankname2Field;
        
        private string bankno1Field;
        
        private string bankno2Field;
        
        private string custnameField;
        
        private string custnoField;
        
        private string idnoField;
        
        private string summaryField;
        
        private string tramtField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accname1
        {
            get
            {
                return this.accname1Field;
            }
            set
            {
                this.accname1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accname2
        {
            get
            {
                return this.accname2Field;
            }
            set
            {
                this.accname2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accno1
        {
            get
            {
                return this.accno1Field;
            }
            set
            {
                this.accno1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accno2
        {
            get
            {
                return this.accno2Field;
            }
            set
            {
                this.accno2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankname1
        {
            get
            {
                return this.bankname1Field;
            }
            set
            {
                this.bankname1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankname2
        {
            get
            {
                return this.bankname2Field;
            }
            set
            {
                this.bankname2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankno1
        {
            get
            {
                return this.bankno1Field;
            }
            set
            {
                this.bankno1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bankno2
        {
            get
            {
                return this.bankno2Field;
            }
            set
            {
                this.bankno2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string custname
        {
            get
            {
                return this.custnameField;
            }
            set
            {
                this.custnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string custno
        {
            get
            {
                return this.custnoField;
            }
            set
            {
                this.custnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idno
        {
            get
            {
                return this.idnoField;
            }
            set
            {
                this.idnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string summary
        {
            get
            {
                return this.summaryField;
            }
            set
            {
                this.summaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tramt
        {
            get
            {
                return this.tramtField;
            }
            set
            {
                this.tramtField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_SB_Qry_Item", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_SB_Qry_Item : LibBatchPlatform.ABC_SB_Item
    {
        
        private string retcodeField;
        
        private string retmsgField;
        
        private string sysdateField;
        
        private string systraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string retcode
        {
            get
            {
                return this.retcodeField;
            }
            set
            {
                this.retcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string retmsg
        {
            get
            {
                return this.retmsgField;
            }
            set
            {
                this.retmsgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sysdate
        {
            get
            {
                return this.sysdateField;
            }
            set
            {
                this.sysdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string systrace
        {
            get
            {
                return this.systraceField;
            }
            set
            {
                this.systraceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_SB_Return", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LibBatchPlatform.ABC_SB_Qry_Res))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LibBatchPlatform.ABC_SB_Submit_Res))]
    public partial class ABC_SB_Return : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string RetCodeField;
        
        private string RetMsgField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RetCode
        {
            get
            {
                return this.RetCodeField;
            }
            set
            {
                this.RetCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RetMsg
        {
            get
            {
                return this.RetMsgField;
            }
            set
            {
                this.RetMsgField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_SB_Qry_Res", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_SB_Qry_Res : LibBatchPlatform.ABC_SB_Return
    {
        
        private LibBatchPlatform.ABC_SB_Qry_Item[] listField;
        
        private string succ_sumField;
        
        private string succ_totalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LibBatchPlatform.ABC_SB_Qry_Item[] list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string succ_sum
        {
            get
            {
                return this.succ_sumField;
            }
            set
            {
                this.succ_sumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string succ_total
        {
            get
            {
                return this.succ_totalField;
            }
            set
            {
                this.succ_totalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_SB_Submit_Res", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_SB_Submit_Res : LibBatchPlatform.ABC_SB_Return
    {
        
        private string BatchNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatchNo
        {
            get
            {
                return this.BatchNoField;
            }
            set
            {
                this.BatchNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ABC_SB_Qry", Namespace="http://schemas.datacontract.org/2004/07/LibBatchPlatform")]
    public partial class ABC_SB_Qry : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string batchnoField;
        
        private string serialField;
        
        private string settdateField;
        
        private string traddrField;
        
        private string trcodeField;
        
        private string trdateField;
        
        private string unitidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string batchno
        {
            get
            {
                return this.batchnoField;
            }
            set
            {
                this.batchnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string serial
        {
            get
            {
                return this.serialField;
            }
            set
            {
                this.serialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string settdate
        {
            get
            {
                return this.settdateField;
            }
            set
            {
                this.settdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string traddr
        {
            get
            {
                return this.traddrField;
            }
            set
            {
                this.traddrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string trcode
        {
            get
            {
                return this.trcodeField;
            }
            set
            {
                this.trcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string trdate
        {
            get
            {
                return this.trdateField;
            }
            set
            {
                this.trdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unitid
        {
            get
            {
                return this.unitidField;
            }
            set
            {
                this.unitidField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService")]
public interface IService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BatchSubmit", ReplyAction="http://tempuri.org/IService/BatchSubmitResponse")]
    LibBatchPlatform.ABC_Batch_Submit_Res BatchSubmit(LibBatchPlatform.ABC_Batch_Submit req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BatchSubmit", ReplyAction="http://tempuri.org/IService/BatchSubmitResponse")]
    System.Threading.Tasks.Task<LibBatchPlatform.ABC_Batch_Submit_Res> BatchSubmitAsync(LibBatchPlatform.ABC_Batch_Submit req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BatchSubmitAsyn", ReplyAction="http://tempuri.org/IService/BatchSubmitAsynResponse")]
    LibBatchPlatform.ABC_Batch_Submit_Res BatchSubmitAsyn(LibBatchPlatform.ABC_Batch_Submit req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BatchSubmitAsyn", ReplyAction="http://tempuri.org/IService/BatchSubmitAsynResponse")]
    System.Threading.Tasks.Task<LibBatchPlatform.ABC_Batch_Submit_Res> BatchSubmitAsynAsync(LibBatchPlatform.ABC_Batch_Submit req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BatchQuery", ReplyAction="http://tempuri.org/IService/BatchQueryResponse")]
    LibBatchPlatform.ABC_Batch_Query_Res BatchQuery(LibBatchPlatform.ABC_Batch_Query req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BatchQuery", ReplyAction="http://tempuri.org/IService/BatchQueryResponse")]
    System.Threading.Tasks.Task<LibBatchPlatform.ABC_Batch_Query_Res> BatchQueryAsync(LibBatchPlatform.ABC_Batch_Query req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ProxySerialTotal", ReplyAction="http://tempuri.org/IService/ProxySerialTotalResponse")]
    LibBatchPlatform.ABC_Serial_Total_Res ProxySerialTotal(LibBatchPlatform.ABC_Serial_Total_Req req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ProxySerialTotal", ReplyAction="http://tempuri.org/IService/ProxySerialTotalResponse")]
    System.Threading.Tasks.Task<LibBatchPlatform.ABC_Serial_Total_Res> ProxySerialTotalAsync(LibBatchPlatform.ABC_Serial_Total_Req req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ProxySerialDetail", ReplyAction="http://tempuri.org/IService/ProxySerialDetailResponse")]
    LibBatchPlatform.ABC_Serial_Detail_Res ProxySerialDetail(LibBatchPlatform.ABC_Serial_Detail_Req req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ProxySerialDetail", ReplyAction="http://tempuri.org/IService/ProxySerialDetailResponse")]
    System.Threading.Tasks.Task<LibBatchPlatform.ABC_Serial_Detail_Res> ProxySerialDetailAsync(LibBatchPlatform.ABC_Serial_Detail_Req req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ProxyOrderRefund", ReplyAction="http://tempuri.org/IService/ProxyOrderRefundResponse")]
    LibBatchPlatform.ABC_Order_Refund_Res ProxyOrderRefund(LibBatchPlatform.ABC_Order_Refund_Req req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ProxyOrderRefund", ReplyAction="http://tempuri.org/IService/ProxyOrderRefundResponse")]
    System.Threading.Tasks.Task<LibBatchPlatform.ABC_Order_Refund_Res> ProxyOrderRefundAsync(LibBatchPlatform.ABC_Order_Refund_Req req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ProxyCheckPayment", ReplyAction="http://tempuri.org/IService/ProxyCheckPaymentResponse")]
    LibBatchPlatform.ABC_Check_Payment_Res ProxyCheckPayment(LibBatchPlatform.ABC_Check_Payment_Req req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ProxyCheckPayment", ReplyAction="http://tempuri.org/IService/ProxyCheckPaymentResponse")]
    System.Threading.Tasks.Task<LibBatchPlatform.ABC_Check_Payment_Res> ProxyCheckPaymentAsync(LibBatchPlatform.ABC_Check_Payment_Req req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BatchResultQuery", ReplyAction="http://tempuri.org/IService/BatchResultQueryResponse")]
    LibBatchPlatform.ABC_Batch_Result_Res BatchResultQuery(LibBatchPlatform.ABC_Batch_Result_Req req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BatchResultQuery", ReplyAction="http://tempuri.org/IService/BatchResultQueryResponse")]
    System.Threading.Tasks.Task<LibBatchPlatform.ABC_Batch_Result_Res> BatchResultQueryAsync(LibBatchPlatform.ABC_Batch_Result_Req req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ProxyVAccoutQuery", ReplyAction="http://tempuri.org/IService/ProxyVAccoutQueryResponse")]
    LibBatchPlatform.ABC_VAccount_Query_Res ProxyVAccoutQuery(LibBatchPlatform.ABC_VAccount_Query_Req req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ProxyVAccoutQuery", ReplyAction="http://tempuri.org/IService/ProxyVAccoutQueryResponse")]
    System.Threading.Tasks.Task<LibBatchPlatform.ABC_VAccount_Query_Res> ProxyVAccoutQueryAsync(LibBatchPlatform.ABC_VAccount_Query_Req req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SBSubmit", ReplyAction="http://tempuri.org/IService/SBSubmitResponse")]
    LibBatchPlatform.ABC_SB_Submit_Res SBSubmit(LibBatchPlatform.ABC_SB_Submit req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SBSubmit", ReplyAction="http://tempuri.org/IService/SBSubmitResponse")]
    System.Threading.Tasks.Task<LibBatchPlatform.ABC_SB_Submit_Res> SBSubmitAsync(LibBatchPlatform.ABC_SB_Submit req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SBQuery", ReplyAction="http://tempuri.org/IService/SBQueryResponse")]
    LibBatchPlatform.ABC_SB_Qry_Res SBQuery(LibBatchPlatform.ABC_SB_Qry req);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SBQuery", ReplyAction="http://tempuri.org/IService/SBQueryResponse")]
    System.Threading.Tasks.Task<LibBatchPlatform.ABC_SB_Qry_Res> SBQueryAsync(LibBatchPlatform.ABC_SB_Qry req);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceChannel : IService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceClient : System.ServiceModel.ClientBase<IService>, IService
{
    
    public ServiceClient()
    {
    }
    
    public ServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public LibBatchPlatform.ABC_Batch_Submit_Res BatchSubmit(LibBatchPlatform.ABC_Batch_Submit req)
    {
        return base.Channel.BatchSubmit(req);
    }
    
    public System.Threading.Tasks.Task<LibBatchPlatform.ABC_Batch_Submit_Res> BatchSubmitAsync(LibBatchPlatform.ABC_Batch_Submit req)
    {
        return base.Channel.BatchSubmitAsync(req);
    }
    
    public LibBatchPlatform.ABC_Batch_Submit_Res BatchSubmitAsyn(LibBatchPlatform.ABC_Batch_Submit req)
    {
        return base.Channel.BatchSubmitAsyn(req);
    }
    
    public System.Threading.Tasks.Task<LibBatchPlatform.ABC_Batch_Submit_Res> BatchSubmitAsynAsync(LibBatchPlatform.ABC_Batch_Submit req)
    {
        return base.Channel.BatchSubmitAsynAsync(req);
    }
    
    public LibBatchPlatform.ABC_Batch_Query_Res BatchQuery(LibBatchPlatform.ABC_Batch_Query req)
    {
        return base.Channel.BatchQuery(req);
    }
    
    public System.Threading.Tasks.Task<LibBatchPlatform.ABC_Batch_Query_Res> BatchQueryAsync(LibBatchPlatform.ABC_Batch_Query req)
    {
        return base.Channel.BatchQueryAsync(req);
    }
    
    public LibBatchPlatform.ABC_Serial_Total_Res ProxySerialTotal(LibBatchPlatform.ABC_Serial_Total_Req req)
    {
        return base.Channel.ProxySerialTotal(req);
    }
    
    public System.Threading.Tasks.Task<LibBatchPlatform.ABC_Serial_Total_Res> ProxySerialTotalAsync(LibBatchPlatform.ABC_Serial_Total_Req req)
    {
        return base.Channel.ProxySerialTotalAsync(req);
    }
    
    public LibBatchPlatform.ABC_Serial_Detail_Res ProxySerialDetail(LibBatchPlatform.ABC_Serial_Detail_Req req)
    {
        return base.Channel.ProxySerialDetail(req);
    }
    
    public System.Threading.Tasks.Task<LibBatchPlatform.ABC_Serial_Detail_Res> ProxySerialDetailAsync(LibBatchPlatform.ABC_Serial_Detail_Req req)
    {
        return base.Channel.ProxySerialDetailAsync(req);
    }
    
    public LibBatchPlatform.ABC_Order_Refund_Res ProxyOrderRefund(LibBatchPlatform.ABC_Order_Refund_Req req)
    {
        return base.Channel.ProxyOrderRefund(req);
    }
    
    public System.Threading.Tasks.Task<LibBatchPlatform.ABC_Order_Refund_Res> ProxyOrderRefundAsync(LibBatchPlatform.ABC_Order_Refund_Req req)
    {
        return base.Channel.ProxyOrderRefundAsync(req);
    }
    
    public LibBatchPlatform.ABC_Check_Payment_Res ProxyCheckPayment(LibBatchPlatform.ABC_Check_Payment_Req req)
    {
        return base.Channel.ProxyCheckPayment(req);
    }
    
    public System.Threading.Tasks.Task<LibBatchPlatform.ABC_Check_Payment_Res> ProxyCheckPaymentAsync(LibBatchPlatform.ABC_Check_Payment_Req req)
    {
        return base.Channel.ProxyCheckPaymentAsync(req);
    }
    
    public LibBatchPlatform.ABC_Batch_Result_Res BatchResultQuery(LibBatchPlatform.ABC_Batch_Result_Req req)
    {
        return base.Channel.BatchResultQuery(req);
    }
    
    public System.Threading.Tasks.Task<LibBatchPlatform.ABC_Batch_Result_Res> BatchResultQueryAsync(LibBatchPlatform.ABC_Batch_Result_Req req)
    {
        return base.Channel.BatchResultQueryAsync(req);
    }
    
    public LibBatchPlatform.ABC_VAccount_Query_Res ProxyVAccoutQuery(LibBatchPlatform.ABC_VAccount_Query_Req req)
    {
        return base.Channel.ProxyVAccoutQuery(req);
    }
    
    public System.Threading.Tasks.Task<LibBatchPlatform.ABC_VAccount_Query_Res> ProxyVAccoutQueryAsync(LibBatchPlatform.ABC_VAccount_Query_Req req)
    {
        return base.Channel.ProxyVAccoutQueryAsync(req);
    }
    
    public LibBatchPlatform.ABC_SB_Submit_Res SBSubmit(LibBatchPlatform.ABC_SB_Submit req)
    {
        return base.Channel.SBSubmit(req);
    }
    
    public System.Threading.Tasks.Task<LibBatchPlatform.ABC_SB_Submit_Res> SBSubmitAsync(LibBatchPlatform.ABC_SB_Submit req)
    {
        return base.Channel.SBSubmitAsync(req);
    }
    
    public LibBatchPlatform.ABC_SB_Qry_Res SBQuery(LibBatchPlatform.ABC_SB_Qry req)
    {
        return base.Channel.SBQuery(req);
    }
    
    public System.Threading.Tasks.Task<LibBatchPlatform.ABC_SB_Qry_Res> SBQueryAsync(LibBatchPlatform.ABC_SB_Qry req)
    {
        return base.Channel.SBQueryAsync(req);
    }
}
